version: 2.0
jobs:
  build:
    docker:
    - image: "circleci/python:latest"

    working_directory: ~/work

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt update
            sudo apt install -y gcc g++ cmake
            sudo pip install -U pip
            sudo pip install cpplint
      - run:
          name: build and test
          command: |
            cd cmake
            cmake ..
            make
            ctest
      - run:
          name: confirm code style
          command: |
            cpplint */*.cc
            cpplint */*.hh
